pitch/models.py
from pitch import db, login_manager
from flask import current_app
from datetime import datetime
from flask_login import UserMixin
# from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    # def get_reset_token(self, expires_sec=1800):
    #     s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
    #     return s.dumps({'user_id':self.id}).decode('utf-8')

    # def verify_reset_token()

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"

class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(), nullable=False)
    data_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    category = db.Column(db.String(), nullable = False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

pitch/pitches/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PitchForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    submit = SubmitField('Pitch')

pitch/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField,PasswordField,SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from pitch.models import User

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField(
        'Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                'Username is taken. Please choose another one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email is taken. Please choose another one')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[
                        FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    'Username is taken. Please choose another one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    'Email is taken. Please choose another one')

pitch/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from config import config_options


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # Registering blueprints
    from pitch.users.routes import users
    from pitch.pitches.routes import pitches
    from pitch.main.routes import main
    from pitch.errors.handlers import errors

    app.register_blueprint(users)
    app.register_blueprint(pitches)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

pitch/main/routes.py
from flask import render_template, request,Blueprint
from pitch.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    pitches = Post.query.order_by(
        Post.data_posted.desc()).paginate(page=page, per_page=4)
    return render_template('home.html', pitches=pitches)


@main.route('/about')
def about():
    title = 'About'
    return render_template('about.html', title=title)

pitch/pitches/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from pitch import db
from pitch.models import Post
from pitch.pitches.forms import PitchForm


pitches = Blueprint('pitches', __name__)


@pitches.route('/pitch/new', methods=['GET', 'POST'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    category=form.category.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_pitch.html', title='New Pitch', form=form, legend='Create Pitch')


@pitches.route('/pitch/<int:post_id>')
def pitch(post_id):
    pitch = Post.query.get_or_404(post_id)
    return render_template('post.html', title=pitch.title, pitch=pitch)


@pitches.route('/pitch/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_pitch(post_id):
    pitch = Post.query.get_or_404(post_id)
    if pitch.author != current_user:
        abort(403)
    form = PitchForm()
    if form.validate_on_submit():
        pitch.title = form.title.data
        pitch.content = form.content.data
        pitch.category = form.category.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('pitches.pitch', post_id=pitch.id))
    elif request.method == 'GET':
        form.title.data = pitch.title
        form.content.data = pitch.content
        form.category.data = pitch.category
    return render_template('create_pitch.html', title='Update Pitch',
                           form=form, legend='Update Post')


@pitches.route('/pitch/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_pitch(post_id):
    pitch = Post.query.get_or_404(post_id)
    if pitch.author != current_user:
        abort(403)
    db.session.delete(pitch)
    db.session.commit()
    flash('Pitch deleted', 'success')
    return redirect(url_for('main.home'))

pitch/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from pitch import db, bcrypt
from pitch.models import User, Post
from pitch.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from pitch.users.utils import save_picture


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_pitch(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    pitches = Post.query.filter_by(author=user)\
        .order_by(Post.data_posted.desc())\
        .paginate(page=page,per_page=4)
    return render_template('user_pitches.html', pitches=pitches, user=user)

pitch/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">About Page.</h1>
        <p class="lead">An application that allows users to submit one minute pitches 
            on any category. The users will submit their one minute pitches and other users will vote on them and leave comments to give their feedback on them.</p>
        <hr class="my-4">
        <p>Users can create account, login and create new pitches in any category.</p>
    </div>
{% endblock %}

pitch/templates/account.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username}}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4"> Account Information</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label")}}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor%}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg")}}
                        {% endif %}
    
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label")}}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor%}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg")}}
                        {% endif %}                
                    </div>
                    <div class="form-group">
                        {{ form.picture.label()}}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form_group">
                    {{ form.submit(class="btn btn-outline-info")}}
                </div>
            </form>
    </div>
{% endblock %}

pitch/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="{{url_for('static', filename='main.css')}}">

    {% if title%}
        <title>Flask {{title}}</title>
    {% else %}
        <title>One Minute Pitch</title>
    {% endif %}

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">1 Minute Pitch</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated%}
                <a class="nav-item nav-link" href="{{url_for('pitches.new_pitch')}}">New Pitch</a>
                <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                {%else%}
                  <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                  <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
            <div class="content-section">
                <h3>One Minute Pitch</h3>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Create Pitch</li>
                    <li class="list-group-item list-group-item-light">View users pitches</li>
                    <li class="list-group-item list-group-item-light">Register</li>
                    <li class="list-group-item list-group-item-light">Login</li>
                </ul>
            </div>
            </div>
        </div>
    </main>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

pitch/templates/create_pitch.html
{% extends 'base.html' %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label")}}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg")}}
                {% endif %}                
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label")}}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                {% else %}
                 {{ form.content(class="form-control form-control-lg")}}
                {% endif %}          
            </div>
            <div class="form-group">
                {{ form.category.label(class="form-control-label")}}
                {% if form.category.errors %}
                    {{ form.category(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.category.errors %}
                            <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                {% else %}
                    {{ form.category(class="form-control form-control-lg")}}
                {% endif %}          
            </div>
        </fieldset>
        <div class="form_group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock %}

pitch/templates/home.html
{% extends 'base.html' %}

{% block content%}

    {% for pitch in pitches.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + pitch.author.image_file)}}" alt="">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_pitch', username=pitch.author.username)}}">{{ pitch.author.username }}</a>
                <small class="text-muted">{{ pitch.data_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('pitches.pitch', post_id=pitch.id)}}">{{ pitch.title }}</a></h2>
            <p class="article-content"> {{ pitch.content }}</p>
            <p class="article-content"><strong>Category:</strong> {{ pitch.category }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in pitches.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num%}
            {% if pitches.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content%}

pitch/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login to your account</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg")}}
                    {% endif %}                
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                     {{ form.password(class="form-control form-control-lg")}}
                    {% endif %}          
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-control-label")}}
                </div>
            </fieldset>
            <div class="form_group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need Have An Account? <a class="ml-2" href="{{url_for('users.register')}}">Sign Up</a>
        </small>
    </div>
{% endblock %}

pitch/templates/post.html
{% extends 'base.html' %}

{% block content%}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + pitch.author.image_file)}}" alt="">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ pitch.author.username }}</a>
            <small class="text-muted">{{ pitch.data_posted.strftime('%Y-%m-%d') }}</small>
            {% if pitch.author == current_user %}
                <div>
                    <a class= "btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('pitches.update_pitch', post_id=pitch.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ pitch.title }}</h2>
        <p class="article-content"><strong>Category:</strong> {{ pitch.category }}</p>
        </div>
    </article>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Pitch?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('pitches.delete_pitch', post_id=pitch.id)}}" method="POST">
                  <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
    </div>
{% endblock content%}

pitch/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label")}}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg")}}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg")}}
                    {% endif %}                
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                     {{ form.password(class="form-control form-control-lg")}}
                    {% endif %}          
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label")}}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg")}}
                    {% endif %}         
                </div>
            </fieldset>
            <div class="form_group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{url_for('users.login')}}">Sign In</a>
        </small>
    </div>
{% endblock %}

pitch/templates/user_pitches.html
{% extends 'base.html' %}

{% block content%}
    <h1 class="mb-3">Pitches by {{ user.username }} ({{ pitches.total}})</h1>
    {% for pitch in pitches.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + pitch.author.image_file)}}" alt="">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_pitch', username=pitch.author.username)}}">{{ pitch.author.username }}</a>
                <small class="text-muted">{{ pitch.data_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('pitches.pitch', post_id=pitch.id)}}">{{ pitch.title }}</a></h2>
            <p class="article-content"> {{ pitch.content }}</p>
            <p class="article-content"><strong>Category:</strong> {{ pitch.category }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in pitches.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num%}
            {% if pitches.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_pitch', username=user.username, page=page_num)}}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_pitch', username=user.username, page=page_num)}}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content%}